# Generated by Django 3.1.3 on 2020-11-23 07:34

import re
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AscendancyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('announced_date', models.DateField()),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'ascendancy',
            },
        ),
        migrations.CreateModel(
            name='CharacterModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('announced_date', models.DateField()),
                ('core_attribute', models.CharField(max_length=45)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'character',
            },
        ),
        migrations.CreateModel(
            name='PassiveSkillModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('skill_type', models.CharField(choices=[('MINOR', 'Minor Skills'), ('MAJOR', 'Major Skills')], max_length=5)),
                ('stats', models.TextField(validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('ascendancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passive_skill', to='content.ascendancymodel')),
            ],
            options={
                'db_table': 'passive_skill',
            },
        ),
        migrations.AddField(
            model_name='ascendancymodel',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ascendancy', to='content.charactermodel'),
        ),
    ]
