name: lint

on:
  pull_request:
    branches:
      - master
      - dev

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Python Linter
      uses: sunnysid3up/python-linter@master
      with:
        source: "poe"
        mypy-options: "--ignore-missing-imports"
        pylint-options: "--rcfile=setup.cfg"
        isort-options: "-w 100"
        django: true